### ISSUE TITLE
Prop for hiding settings button in edit mode

### ISSUE THREAD

**Issue by St1ggy** [gravity-ui/dashkit#144]
Context menu button in Editing mode doesn't have a border radius on the left part of the button when hovered over

Mac OS 14.4.1 (23E224)
Yandex Browser 24.1.5.827 (64-bit) | Safari 17.4.1 (19618.1.15.11.14)

<img width="182" alt="image" src="https://github.com/gravity-ui/dashkit/assets/13361661/e7696942-a8a7-48d2-a56c-e2512eab57ad">

**Comment by korvin89** [comment]
cc @Marginy605 @jhoncool

**Comment by Marginy605** [comment]
@St1ggy I can't reproduce case with only one menu button. There is more than one in all storybook cases:
![image](https://github.com/gravity-ui/dashkit/assets/98329176/2de3fc27-0ebe-4727-964d-12178a5ed810)

Could you show a code sample of that way of configuring menu?

**Comment by St1ggy** [comment]
This is our local problem, we hide the gear in css, sorry :)

**Comment by Marginy605** [comment]
> This is our local problem, we hide the gear in css, sorry :)

Perhaps you need some prop in Dashkit to hide gear button?

Modifying inner component styles is not a good option cause any component update could broke you appearance. It's always better change it via official component css-api or some prop.

**Comment by St1ggy** [comment]
> @St1ggy
> 
> > This is our local problem, we hide the gear in css, sorry :)
> 
> Perhaps you need some prop in Dashkit to hide gear button?
> 
> Modifying inner component styles is not a good option cause any component update could broke you appearance. It's always better change it via official component css-api or some prop.

I think it sounds good :)
If this feature will not be linked to this issue, close it, please :)
